// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/key/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/key/repository.go -destination=internal/repository/key/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	key "github.com/kitanoyoru/kgym/internal/apps/sso/internal/entity/key"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetCurrentSigningKey mocks base method.
func (m *MockIRepository) GetCurrentSigningKey(ctx context.Context) (key.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentSigningKey", ctx)
	ret0, _ := ret[0].(key.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentSigningKey indicates an expected call of GetCurrentSigningKey.
func (mr *MockIRepositoryMockRecorder) GetCurrentSigningKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentSigningKey", reflect.TypeOf((*MockIRepository)(nil).GetCurrentSigningKey), ctx)
}

// GetPublicKeys mocks base method.
func (m *MockIRepository) GetPublicKeys(ctx context.Context) ([]key.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKeys", ctx)
	ret0, _ := ret[0].([]key.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKeys indicates an expected call of GetPublicKeys.
func (mr *MockIRepositoryMockRecorder) GetPublicKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKeys", reflect.TypeOf((*MockIRepository)(nil).GetPublicKeys), ctx)
}

// Rotate mocks base method.
func (m *MockIRepository) Rotate(ctx context.Context) (key.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx)
	ret0, _ := ret[0].(key.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rotate indicates an expected call of Rotate.
func (mr *MockIRepositoryMockRecorder) Rotate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockIRepository)(nil).Rotate), ctx)
}
